name = "trader-hub-api"
main = "src/index.ts"
compatibility_date = "2025-12-15"

[vars]
APP_SECRET = "CHANGE_ME_TO_A_LONG_RANDOM_SECRET_20+CHARS"
FINNHUB_API_KEY = ""
POLYGON_API_KEY = ""
DATA_PROVIDER = "finnhub"

[[d1_databases]]
binding = "DB"
database_name = "trader_hub"
database_id = "ea148a16-fc94-4f7b-a182-d320d678d490"

[triggers]
crons = ["*/15 * * * *"]
